import chai from 'chai'
import {PokemonType} from '../../src/util/PokemonType.js'

var assert = chai.assert

describe('PokemonType test', () => {
    it('We can create a PokemonType', function(){
        let pokemonType = new PokemonType({normal:0, flying:3, ghost: 0}, {electric: 3, ghost: 0, fire: 1})
        assert(pokemonType.offense.normal === 0)
        assert(pokemonType.offense.fighting === 1)
        assert(pokemonType.offense.flying === 3)
        assert(pokemonType.offense.poison === 1)
        assert(pokemonType.offense.ground === 1)
        assert(pokemonType.offense.rock === 1)
        assert(pokemonType.offense.bug === 1)
        assert(pokemonType.offense.ghost === 0)
        assert(pokemonType.offense.steel === 1)
        assert(pokemonType.offense.fire === 1)
        assert(pokemonType.offense.water === 1)
        assert(pokemonType.offense.grass === 1)
        assert(pokemonType.offense.electric === 1)
        assert(pokemonType.offense.steel === 1)
        assert(pokemonType.offense.psychic === 1)
        assert(pokemonType.offense.ice === 1)
        assert(pokemonType.offense.dragon === 1)
        assert(pokemonType.offense.dark === 1)
        assert(pokemonType.offense.fairy === 1)
        
        assert(pokemonType.defense.normal === 1)
        assert(pokemonType.defense.fighting === 1)
        assert(pokemonType.defense.flying === 1)
        assert(pokemonType.defense.poison === 1)
        assert(pokemonType.defense.ground === 1)
        assert(pokemonType.defense.rock === 1)
        assert(pokemonType.defense.bug === 1)
        assert(pokemonType.defense.ghost === 0)
        assert(pokemonType.defense.steel === 1)
        assert(pokemonType.defense.fire === 1)
        assert(pokemonType.defense.water === 1)
        assert(pokemonType.defense.grass === 1)
        assert(pokemonType.defense.electric === 3)
        assert(pokemonType.defense.steel === 1)
        assert(pokemonType.defense.psychic === 1)
        assert(pokemonType.defense.ice === 1)
        assert(pokemonType.defense.dragon === 1)
        assert(pokemonType.defense.dark === 1)
        assert(pokemonType.defense.fairy === 1)
    })
    
    it('We can multiply PokemonTypes', function(){
        let pokemonType1 = new PokemonType({normal: 2, ghost: 2}, {flying: 0, steel: 2})
        let pokemonType2 = new PokemonType({ghost: 2}, {steel: .5})
        
        pokemonType1.multiply(pokemonType2)
        
        let pokemonTypeResult = new PokemonType({normal: 2, ghost: 4}, {flying: 0})
        
        assert(pokemonType1.offense.normal === 2)
        assert(pokemonType1.offense.fighting === 1)
        assert(pokemonType1.offense.flying === 1)
        assert(pokemonType1.offense.poison === 1)
        assert(pokemonType1.offense.ground === 1)
        assert(pokemonType1.offense.rock === 1)
        assert(pokemonType1.offense.bug === 1)
        assert(pokemonType1.offense.ghost === 4)
        assert(pokemonType1.offense.steel === 1)
        assert(pokemonType1.offense.fire === 1)
        assert(pokemonType1.offense.water === 1)
        assert(pokemonType1.offense.grass === 1)
        assert(pokemonType1.offense.electric === 1)
        assert(pokemonType1.offense.steel === 1)
        assert(pokemonType1.offense.psychic === 1)
        assert(pokemonType1.offense.ice === 1)
        assert(pokemonType1.offense.dragon === 1)
        assert(pokemonType1.offense.dark === 1)
        assert(pokemonType1.offense.fairy === 1)
        
        assert(pokemonType1.defense.normal === 1)
        assert(pokemonType1.defense.fighting === 1)
        assert(pokemonType1.defense.flying === 0)
        assert(pokemonType1.defense.poison === 1)
        assert(pokemonType1.defense.ground === 1)
        assert(pokemonType1.defense.rock === 1)
        assert(pokemonType1.defense.bug === 1)
        assert(pokemonType1.defense.ghost === 1)
        assert(pokemonType1.defense.steel === 1)
        assert(pokemonType1.defense.fire === 1)
        assert(pokemonType1.defense.water === 1)
        assert(pokemonType1.defense.grass === 1)
        assert(pokemonType1.defense.electric === 1)
        assert(pokemonType1.defense.steel === 1)
        assert(pokemonType1.defense.psychic === 1)
        assert(pokemonType1.defense.ice === 1)
        assert(pokemonType1.defense.dragon === 1)
        assert(pokemonType1.defense.dark === 1)
        assert(pokemonType1.defense.fairy === 1)
    })
})